# Generated by scripts/update-formula.sh — do not edit by hand.
class Tandem < Formula
  desc "A shared seat inside your coding-agent session"
  homepage "https://github.com/mherzog4/tandem"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mherzog4/tandem/releases/download/v0.5.0/tandem-darwin-arm64"
      sha256 "12bb544e7e7944eaf25c47d0b02c845a832b2757c2705bf35e905b2e8f93f9be"
    end
    on_intel do
      url "https://github.com/mherzog4/tandem/releases/download/v0.5.0/tandem-darwin-amd64"
      sha256 "1d8b5c1f440c4ddc7ac220cf5e9d825eda2ee08b491f6dcfd87968f85c029f13"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mherzog4/tandem/releases/download/v0.5.0/tandem-linux-arm64"
      sha256 "8ce4db985fe542ebac1c2e59c003fecca34300d9007685fc01ffda5b3adbfec0"
    end
    on_intel do
      url "https://github.com/mherzog4/tandem/releases/download/v0.5.0/tandem-linux-amd64"
      sha256 "6cfeb347eb57893e76359e0f2f68338104822d9b368e948ad30538ef94c80ce3"
    end
  end

  def install
    bin.install Dir["*"].first => "tandem"
  end

  test do
    assert_match "tandem", shell_output("#{bin}/tandem --version")
  end
end
