# Generated by scripts/update-formula.sh — do not edit by hand.
class Tandem < Formula
  desc "A shared seat inside your coding-agent session"
  homepage "https://github.com/mherzog4/tandem"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mherzog4/tandem/releases/download/v0.4.0/tandem-darwin-arm64"
      sha256 "6a7ae7b8a56c10842b731a99a186c6e692241a7824a06a6d0c1bdae0ddca56d8"
    end
    on_intel do
      url "https://github.com/mherzog4/tandem/releases/download/v0.4.0/tandem-darwin-amd64"
      sha256 "a3418614b14d70f2a8fedc390170b4a2b328ea383e508a8bc0569774ee12599c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mherzog4/tandem/releases/download/v0.4.0/tandem-linux-arm64"
      sha256 "64841d9bd601132000d29221036c697ce3639982dfd6384b1608669a1b0e0bc6"
    end
    on_intel do
      url "https://github.com/mherzog4/tandem/releases/download/v0.4.0/tandem-linux-amd64"
      sha256 "b2d587e71bdba7964f8d67542e2ed1cb2dcbc96de6864d79cd7844711f75582c"
    end
  end

  def install
    bin.install Dir["*"].first => "tandem"
  end

  test do
    assert_match "tandem", shell_output("#{bin}/tandem --version")
  end
end
