// Package domainfile serializes confirmed Domain Board cards into the
// wrapped repository (FR14): DOMAIN.md for humans and agents that read
// markdown context, domain.yaml as the machine-readable form the next
// session preloads (FR20).
//
// Output is deterministic — board order, no timestamps — so
// re-confirming without changes produces no diff, and writes are
// skipped entirely when content is unchanged.
package domainfile

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mherzog4/tandem/internal/board"
)

const (
	MarkdownName = "DOMAIN.md"
	YAMLName     = "domain.yaml"
	// SchemaVersion guards domain.yaml evolution (documented below in
	// RenderYAML's header).
	SchemaVersion = 1
)

var sections = []struct {
	cardType, yamlKey, mdTitle string
}{
	{board.TypeEvent, "events", "Domain Events (process order)"},
	{board.TypeCmd, "commands", "Commands"},
	{board.TypeActor, "actors", "Actors & Roles"},
	{board.TypeTerm, "terms", "Terms & Rules"},
}

func confirmed(cards []board.Card) []board.Card {
	var out []board.Card
	for _, c := range cards {
		if c.State == board.StateConfirmed {
			out = append(out, c)
		}
	}
	return out
}

// RenderMarkdown produces DOMAIN.md content.
func RenderMarkdown(cards []board.Card) string {
	cc := confirmed(cards)
	var b strings.Builder
	b.WriteString("# Domain model\n\n")
	b.WriteString("Ubiquitous language for this repository, built in Tandem sessions\n")
	b.WriteString("by the people who own the domain. The business wording is\n")
	b.WriteString("authoritative; `code:` aliases map terms to code constructs.\n")
	b.WriteString("Name new code constructs after these terms.\n")
	for _, sec := range sections {
		var lines []string
		for _, c := range cc {
			if c.Type != sec.cardType {
				continue
			}
			l := "- " + c.Text
			if c.CodeName != "" {
				l += " (code: `" + c.CodeName + "`)"
			}
			lines = append(lines, l)
		}
		if len(lines) == 0 {
			continue
		}
		b.WriteString("\n## " + sec.mdTitle + "\n\n")
		b.WriteString(strings.Join(lines, "\n") + "\n")
	}
	return b.String()
}

// RenderYAML produces domain.yaml content. Strings are JSON-quoted,
// which is valid YAML and sidesteps escaping edge cases.
func RenderYAML(cards []board.Card) string {
	cc := confirmed(cards)
	var b strings.Builder
	b.WriteString("# generated by tandem — confirmed domain model (do not hand-edit card IDs)\n")
	fmt.Fprintf(&b, "version: %d\n", SchemaVersion)
	for _, sec := range sections {
		var entries []board.Card
		for _, c := range cc {
			if c.Type == sec.cardType {
				entries = append(entries, c)
			}
		}
		if len(entries) == 0 {
			continue
		}
		b.WriteString(sec.yamlKey + ":\n")
		for _, c := range entries {
			fmt.Fprintf(&b, "  - id: %s\n", strconv.Quote(c.ID))
			fmt.Fprintf(&b, "    name: %s\n", strconv.Quote(c.Text))
			if c.CodeName != "" {
				fmt.Fprintf(&b, "    code: %s\n", strconv.Quote(c.CodeName))
			}
			fmt.Fprintf(&b, "    author: %s\n", strconv.Quote(c.Author))
		}
	}
	return b.String()
}

// WriteFiles updates DOMAIN.md and domain.yaml in dir, skipping writes
// whose content is unchanged. Files are only created once at least one
// card has been confirmed — Tandem never litters a repo it was merely
// pointed at. Returns whether anything was written.
func WriteFiles(dir string, cards []board.Card) (bool, error) {
	if len(confirmed(cards)) == 0 {
		if _, err := os.Stat(filepath.Join(dir, YAMLName)); err != nil {
			return false, nil // nothing confirmed, nothing pre-existing
		}
	}
	wrote := false
	for name, content := range map[string]string{
		MarkdownName: RenderMarkdown(cards),
		YAMLName:     RenderYAML(cards),
	} {
		path := filepath.Join(dir, name)
		if old, err := os.ReadFile(path); err == nil && string(old) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return wrote, err
		}
		wrote = true
	}
	return wrote, nil
}
