#!/bin/sh
# Regenerate the Homebrew formula for a released version by fetching the
# published binaries and hashing them. Prints the formula to stdout.
#   scripts/update-formula.sh v0.4.0 > Formula/tandem.rb
set -eu

VERSION="${1:?usage: update-formula.sh vX.Y.Z}"
case "$VERSION" in v*) ;; *) echo "version must start with v" >&2; exit 1 ;; esac
REPO="mherzog4/tandem"
BASE="https://github.com/$REPO/releases/download/$VERSION"

sha() {
  tmp=$(mktemp)
  curl -fsSL "$BASE/tandem-$1" -o "$tmp"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$tmp" | cut -d' ' -f1
  else
    sha256sum "$tmp" | cut -d' ' -f1
  fi
  rm -f "$tmp"
}

DA=$(sha darwin-arm64)
DI=$(sha darwin-amd64)
LA=$(sha linux-arm64)
LI=$(sha linux-amd64)

cat <<RUBY
# Generated by scripts/update-formula.sh — do not edit by hand.
class Tandem < Formula
  desc "A shared seat inside your coding-agent session"
  homepage "https://github.com/$REPO"
  version "${VERSION#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE/tandem-darwin-arm64"
      sha256 "$DA"
    end
    on_intel do
      url "$BASE/tandem-darwin-amd64"
      sha256 "$DI"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/tandem-linux-arm64"
      sha256 "$LA"
    end
    on_intel do
      url "$BASE/tandem-linux-amd64"
      sha256 "$LI"
    end
  end

  def install
    bin.install Dir["*"].first => "tandem"
  end

  test do
    assert_match "tandem", shell_output("#{bin}/tandem --version")
  end
end
RUBY
